version: "3.10"

services:
  app:
    build:
      context: .
    restart: always
    container_name: property_management_app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - SPRING_PROFILES_ACTIVE=deployment
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network

  db:
    build:
      context: -./database
    container_name: property_management_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER= ${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./database/init-scripts:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:

volumes:
  pg_data:
